//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pofo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutPage
    {
        public int Id { get; set; }
        public string LeftPreTitle { get; set; }
        public string LeftTitle { get; set; }
        public string LeftText { get; set; }
        public string RightPreText { get; set; }
        public string OverviewTitle { get; set; }
        public string OverViewVideo { get; set; }
        public string OverViewBgPic { get; set; }
        public string MainSlogan { get; set; }
        public Nullable<int> LangId { get; set; }
    
        public virtual Languages Languages { get; set; }
    }
}
