//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pofo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleBlog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SingleBlog()
        {
            this.BlogPhotos = new HashSet<BlogPhotos>();
            this.BlogTags = new HashSet<BlogTags>();
            this.Comments = new HashSet<Comments>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string IntroPhoto { get; set; }
        public string BlockVoteText { get; set; }
        public string BlockVoteAutHor { get; set; }
        public Nullable<int> Count { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string CenterPhoto { get; set; }
        public string LeftPhoto { get; set; }
        public Nullable<int> LangId { get; set; }
        public string AfterCenterPhotoText { get; set; }
        public string LeftPhotoText { get; set; }
    
        public virtual BloggCategories BloggCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogPhotos> BlogPhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogTags> BlogTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Languages Languages { get; set; }
    }
}
